Repository TEAM-Encore/SPRING-BACKEND, pull requests merged in 2024-11, with the labels that each got.

#5 Feat: Post 엔티티 수정 (공지사항 여부와 임시저장 여부 필드 추가)
  src/main/java/encore/server/domain/post/entity/Post.java
Labels: ✨ Feature

#9 Feat: 댓글(대댓글) 생성/수정/조회/삭제 API
  src/main/java/encore/server/EncoreServerApplication.java
  src/main/java/encore/server/domain/comment/controller/CommentController.java
  src/main/java/encore/server/domain/comment/converter/CommentConverter.java
  src/main/java/encore/server/domain/comment/dto/request/CommentReq.java
  src/main/java/encore/server/domain/comment/dto/response/CommentRes.java
  src/main/java/encore/server/domain/comment/entity/Comment.java
  src/main/java/encore/server/domain/comment/repository/CommentRepository.java
  src/main/java/encore/server/domain/comment/service/CommentService.java
  src/main/java/encore/server/domain/post/repository/PostRepository.java
  src/main/java/encore/server/domain/user/repository/UserRepository.java
  src/main/java/encore/server/global/exception/ErrorCode.java
Labels: ✨ Feature

#15 Fix: 이미지 패키지 및 엔드포인트 수정
  src/main/java/encore/server/domain/comment/controller/CommentController.java
  src/main/java/encore/server/domain/image/controller/ImageController.java
  src/main/java/encore/server/domain/image/dto/ImageNameDTO.java
  src/main/java/encore/server/domain/image/service/ImageService.java
Labels: 🎀 Fix

#14 Feat: 게시글 CRUD API
  build.gradle
  src/main/java/encore/server/domain/comment/repository/CommentRepository.java
  src/main/java/encore/server/domain/hashtag/converter/PostHashtagConverter.java
  src/main/java/encore/server/domain/hashtag/entity/Hashtag.java
  src/main/java/encore/server/domain/hashtag/entity/PostHashtag.java
  src/main/java/encore/server/domain/hashtag/repository/HashtagRepository.java
  src/main/java/encore/server/domain/hashtag/repository/PostHashtagRepository.java
  src/main/java/encore/server/domain/post/controller/PostController.java
  src/main/java/encore/server/domain/post/converter/PostConverter.java
  src/main/java/encore/server/domain/post/converter/PostImageConverter.java
  src/main/java/encore/server/domain/post/dto/request/PostCreateReq.java
  src/main/java/encore/server/domain/post/dto/request/PostUpdateReq.java
  src/main/java/encore/server/domain/post/dto/response/PostDetailsGetRes.java
  src/main/java/encore/server/domain/post/entity/Post.java
  src/main/java/encore/server/domain/post/repository/PostImageRepository.java
  src/main/java/encore/server/domain/post/repository/PostLikeRepository.java
  src/main/java/encore/server/domain/post/repository/PostRepository.java
  src/main/java/encore/server/domain/post/service/PostService.java
  src/main/java/encore/server/global/exception/BadRequestException.java
  src/main/java/encore/server/global/exception/GlobalExceptionHandler.java
  src/main/java/encore/server/global/exception/UserNotFoundException.java
  src/test/java/encore/server/domain/post/service/PostServiceTest.java
Labels: ✨ Feature

#18 Feat: 게시판 커서 기반 페이지네이션
  src/main/java/encore/server/domain/image/controller/ImageController.java
  src/main/java/encore/server/domain/post/controller/PostController.java
  src/main/java/encore/server/domain/post/converter/PostConverter.java
  src/main/java/encore/server/domain/post/dto/response/SimplePostRes.java
  src/main/java/encore/server/domain/post/entity/Post.java
  src/main/java/encore/server/domain/post/repository/PostRepository.java
  src/main/java/encore/server/domain/post/repository/PostRepositoryCustom.java
  src/main/java/encore/server/domain/post/repository/PostRepositoryImpl.java
  src/main/java/encore/server/domain/post/service/PostService.java
  src/main/java/encore/server/domain/user/entity/User.java
Labels: ✨ Feature

#19 Fix: Operation 추가
  src/main/java/encore/server/domain/comment/controller/CommentController.java
  src/main/java/encore/server/domain/post/controller/PostController.java
Labels: 🎀 Fix

#20 Fix: 수정사항 반영
  src/main/java/encore/server/domain/post/controller/PostController.java
  src/main/java/encore/server/domain/post/converter/PostConverter.java
  src/main/java/encore/server/domain/post/dto/response/PostDetailsGetRes.java
  src/main/java/encore/server/domain/post/dto/response/SimplePostRes.java
  src/main/java/encore/server/domain/post/repository/PostRepositoryImpl.java
  src/main/java/encore/server/domain/post/service/PostService.java
  src/main/java/encore/server/domain/user/entity/User.java
Labels: ✨ Feature

#21 Feat/#10 post like edit
  docker-compose.yml
  gradlew
  src/main/java/encore/server/domain/post/controller/PostController.java
  src/main/java/encore/server/domain/post/dto/request/PostLikeReq.java
  src/main/java/encore/server/domain/post/entity/PostLike.java
  src/main/java/encore/server/domain/post/repository/PostLikeRepository.java
  src/main/java/encore/server/domain/post/repository/PostRepository.java
  src/main/java/encore/server/domain/post/service/PostLikeService.java
  src/main/resources/application.yml
Labels: ✨ Feature, 🎀 Fix

#27 Feat: 댓글 좋아요 API
  src/main/java/encore/server/domain/comment/controller/CommentController.java
  src/main/java/encore/server/domain/comment/converter/CommentConverter.java
  src/main/java/encore/server/domain/comment/dto/response/CommentLikeRes.java
  src/main/java/encore/server/domain/comment/dto/response/CommentRes.java
  src/main/java/encore/server/domain/comment/entity/Comment.java
  src/main/java/encore/server/domain/comment/entity/CommentLike.java
  src/main/java/encore/server/domain/comment/repository/CommentLikeRepository.java
  src/main/java/encore/server/domain/comment/repository/CommentRepository.java
  src/main/java/encore/server/domain/comment/service/CommentService.java
Labels: ✨ Feature

#31 #30 Fix: 전체 조회 좋아요 갯수 반환
  .gitignore
  src/main/java/encore/server/domain/post/controller/PostController.java
  src/main/java/encore/server/domain/post/converter/PostConverter.java
  src/main/java/encore/server/domain/post/dto/response/SimplePostRes.java
  src/main/java/encore/server/domain/post/entity/Post.java
  src/main/java/encore/server/domain/post/repository/PostLikeRepository.java
  src/main/java/encore/server/domain/post/service/PostLikeService.java
  src/main/java/encore/server/domain/post/service/PostService.java
Labels: 🎀 Fix

#33 #32 Fix: PostConverter의 toSimplePostRes 변경
  src/main/java/encore/server/domain/post/converter/PostConverter.java
Labels: 🐞 BugFix

#35 Feat: 게시글 작성 시 뮤지컬 용어 함께 반환
  src/main/java/encore/server/domain/comment/repository/CommentRepository.java
  src/main/java/encore/server/domain/comment/service/CommentService.java
  src/main/java/encore/server/domain/post/converter/PostConverter.java
  src/main/java/encore/server/domain/post/dto/response/PostDetailsGetRes.java
  src/main/java/encore/server/domain/post/dto/response/SimplePostRes.java
  src/main/java/encore/server/domain/post/entity/Post.java
  src/main/java/encore/server/domain/post/repository/PostRepositoryCustom.java
  src/main/java/encore/server/domain/post/repository/PostRepositoryImpl.java
  src/main/java/encore/server/domain/post/service/PostService.java
  src/main/java/encore/server/domain/term/converter/MusicalTermConverter.java
  src/main/java/encore/server/domain/term/dto/MusicalTermRes.java
  src/main/java/encore/server/domain/term/entity/Term.java
  src/main/java/encore/server/domain/term/repository/TermRepository.java
  src/main/java/encore/server/domain/term/repository/TermRepositoryCustom.java
  src/main/java/encore/server/domain/term/repository/TermRepositoryImpl.java
Labels: ✨ Feature
