Repository TEAM-Encore/SPRING-BACKEND, pull requests merged in 2025-01, with the labels that each got.

#64 Feat: 구글 로그인 개발
  build.gradle
  src/main/java/encore/server/domain/user/controller/UserController.java
  src/main/java/encore/server/domain/user/converter/UserConverter.java
  src/main/java/encore/server/domain/user/dto/request/UserLoginReq.java
  src/main/java/encore/server/domain/user/dto/request/UserSignupReq.java
  src/main/java/encore/server/domain/user/dto/response/UserLoginRes.java
  src/main/java/encore/server/domain/user/dto/response/UserSignupRes.java
  src/main/java/encore/server/domain/user/entity/PreferredKeyword.java
  src/main/java/encore/server/domain/user/entity/TermOfUse.java
  src/main/java/encore/server/domain/user/entity/User.java
  src/main/java/encore/server/domain/user/entity/UserKeyword.java
  src/main/java/encore/server/domain/user/entity/UserTermOfUse.java
  src/main/java/encore/server/domain/user/enumerate/AuthProvider.java
  src/main/java/encore/server/domain/user/enumerate/PreferredKeywordEnum.java
  src/main/java/encore/server/domain/user/enumerate/UserRole.java
  src/main/java/encore/server/domain/user/enumerate/ViewingFrequency.java
  src/main/java/encore/server/domain/user/repository/TermOfUseRepository.java
  src/main/java/encore/server/domain/user/repository/UserRepository.java
  src/main/java/encore/server/domain/user/service/UserService.java
  src/main/java/encore/server/global/auth/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/encore/server/global/auth/OAuth2SuccessHandler.java
  src/main/java/encore/server/global/auth/OAuth2UserInfo.java
  src/main/java/encore/server/global/auth/OAuth2UserService.java
  src/main/java/encore/server/global/config/CorsConfig.java
  src/main/java/encore/server/global/config/PasswordConfig.java
  src/main/java/encore/server/global/config/SecurityConfig.java
  src/main/java/encore/server/global/exception/ErrorCode.java
  src/main/java/encore/server/global/util/CookieUtils.java
  src/main/java/encore/server/global/util/JwtUtil.java
  src/main/java/encore/server/global/util/OAuth2UserInfoMaker.java
Labels: ✨ Feature

#65 뮤지컬 상세조회 API 구현
  src/main/java/encore/server/domain/musical/controller/MusicalController.java
  src/main/java/encore/server/domain/musical/converter/MusicalConverter.java
  src/main/java/encore/server/domain/musical/dto/response/MusicalDetailRes.java
  src/main/java/encore/server/domain/musical/dto/response/MusicalSeriesRes.java
  src/main/java/encore/server/domain/musical/entity/Musical.java
  src/main/java/encore/server/domain/musical/entity/MusicalActor.java
  src/main/java/encore/server/domain/musical/repository/MusicalRepository.java
  src/main/java/encore/server/domain/musical/service/MusicalService.java
  src/main/java/encore/server/domain/review/controller/ReviewController.java
  src/main/java/encore/server/domain/review/converter/ReviewConverter.java
  src/main/java/encore/server/domain/review/dto/response/ReviewRes.java
  src/main/java/encore/server/domain/review/dto/response/ReviewSummaryRes.java
  src/main/java/encore/server/domain/review/repository/ReviewRepository.java
  src/main/java/encore/server/domain/review/service/ReviewService.java
  src/main/java/encore/server/domain/ticket/entity/Actor.java
Labels: ✨ Feature

#67 이달의 인기 뮤지컬/ 개봉 예정 뮤지컬 조회 API
  src/main/java/encore/server/domain/musical/controller/MusicalController.java
  src/main/java/encore/server/domain/musical/dto/response/MusicalSimpleRes.java
  src/main/java/encore/server/domain/musical/entity/Musical.java
  src/main/java/encore/server/domain/musical/repository/MusicalRepository.java
  src/main/java/encore/server/domain/musical/service/MusicalService.java
Labels: ✨ Feature

#71 Feat: 리뷰 좋아요 기획 변경 사항 반영
  src/main/java/encore/server/domain/review/controller/ReviewController.java
  src/main/java/encore/server/domain/review/converter/ReviewConverter.java
  src/main/java/encore/server/domain/review/dto/response/ReviewDataRes.java
  src/main/java/encore/server/domain/review/dto/response/ReviewDetailRes.java
  src/main/java/encore/server/domain/review/dto/response/ReviewLikeRes.java
  src/main/java/encore/server/domain/review/dto/response/ReviewPreviewRes.java
  src/main/java/encore/server/domain/review/dto/response/ReviewSimpleRes.java
  src/main/java/encore/server/domain/review/dto/response/ViewImageRes.java
  src/main/java/encore/server/domain/review/entity/Review.java
  src/main/java/encore/server/domain/review/entity/ReviewLike.java
  src/main/java/encore/server/domain/review/enumerate/LikeType.java
  src/main/java/encore/server/domain/review/mapping/LikeTypeMapping.java
  src/main/java/encore/server/domain/review/repository/ReviewLikeRepository.java
  src/main/java/encore/server/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/encore/server/domain/review/service/ReviewService.java
  src/main/java/encore/server/global/exception/ErrorCode.java
Labels: ✨ Feature

#68 Feat: 리뷰 수정/삭제/신고하기 API
  src/main/java/encore/server/domain/review/controller/ReviewController.java
  src/main/java/encore/server/domain/review/converter/ReviewConverter.java
  src/main/java/encore/server/domain/review/dto/response/ReviewReportRes.java
  src/main/java/encore/server/domain/review/entity/Review.java
  src/main/java/encore/server/domain/review/entity/ReviewReport.java
  src/main/java/encore/server/domain/review/enumerate/ReportReason.java
  src/main/java/encore/server/domain/review/repository/ReviewReportRepository.java
  src/main/java/encore/server/domain/review/service/ReviewService.java
  src/main/java/encore/server/domain/term/repository/TermRepositoryImpl.java
  src/main/java/encore/server/global/exception/ErrorCode.java
Labels: ✨ Feature

#77 fix: cast error
  src/main/java/encore/server/domain/review/service/ReviewService.java
Labels: 🐞 BugFix

#75 Feat: komoran, redis를 이용한 검색어 자동완성 기능 개발
  build.gradle
  src/main/java/encore/server/domain/musical/converter/MusicalConverter.java
  src/main/java/encore/server/domain/musical/dto/response/MusicalRes.java
  src/main/java/encore/server/domain/post/controller/PostController.java
  src/main/java/encore/server/domain/post/repository/PostRepositoryCustom.java
  src/main/java/encore/server/domain/post/repository/PostRepositoryImpl.java
  src/main/java/encore/server/domain/post/service/PostRelatedSearchService.java
  src/main/java/encore/server/domain/review/controller/ReviewController.java
  src/main/java/encore/server/domain/review/dto/request/ReviewReq.java
  src/main/java/encore/server/domain/review/dto/response/ReviewLikeRes.java
  src/main/java/encore/server/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/encore/server/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/encore/server/domain/review/service/ReviewRecentSearchService.java
  src/main/java/encore/server/domain/review/service/ReviewRelatedSearchService.java
  src/main/java/encore/server/domain/review/service/ReviewService.java
  src/main/java/encore/server/domain/search/controller/SearchController.java
  src/main/java/encore/server/domain/ticket/controller/TicketController.java
  src/main/java/encore/server/domain/ticket/converter/TicketConverter.java
  src/main/java/encore/server/domain/ticket/dto/response/TicketSimpleRes.java
  src/main/java/encore/server/domain/ticket/repository/TicketRepository.java
  src/main/java/encore/server/domain/ticket/service/TicketService.java
  src/main/java/encore/server/global/common/ExtractNouns.java
  src/main/java/encore/server/global/config/RedisConfig.java
Labels: ✨ Feature

#81 Feat : 온보딩 페이지에서 필요한 API 구현
  src/main/java/encore/server/domain/post/repository/PostRepository.java
  src/main/java/encore/server/domain/user/controller/UserController.java
  src/main/java/encore/server/domain/user/converter/UserConverter.java
  src/main/java/encore/server/domain/user/dto/request/UserPatchReq.java
  src/main/java/encore/server/domain/user/dto/response/UserGetMeRes.java
  src/main/java/encore/server/domain/user/dto/response/UserNicknameValidationRes.java
  src/main/java/encore/server/domain/user/entity/PreferredKeyword.java
  src/main/java/encore/server/domain/user/entity/TermOfUse.java
  src/main/java/encore/server/domain/user/entity/User.java
  src/main/java/encore/server/domain/user/entity/UserKeyword.java
  src/main/java/encore/server/domain/user/entity/UserTermOfUse.java
  src/main/java/encore/server/domain/user/enumerate/TermType.java
  src/main/java/encore/server/domain/user/enumerate/ViewingFrequency.java
  src/main/java/encore/server/domain/user/repository/PreferredKeywordRepository.java
  src/main/java/encore/server/domain/user/repository/TermOfUseRepository.java
  src/main/java/encore/server/domain/user/repository/UserKeywordRepository.java
  src/main/java/encore/server/domain/user/repository/UserTermOfUseRepository.java
  src/main/java/encore/server/domain/user/service/UserAuthService.java
  src/main/java/encore/server/domain/user/service/UserInfoService.java
  src/main/java/encore/server/domain/user/service/UserSetupService.java
  src/main/java/encore/server/global/auth/OAuth2SuccessHandler.java
  src/main/java/encore/server/global/exception/ErrorCode.java
Labels: ✨ Feature

#83 Chore: 잇타 제공 서버 포트로 재배포
  .github/workflows/cicd.yml
  src/main/java/encore/server/domain/review/service/ReviewService.java
Labels: 🌏 Deploy

#85 Deploy: CI/CD 분리
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: 🌏 Deploy

#89 Chore: 로그수집 & 모니터링 환경 구축
  build.gradle
Labels: 🛠️ Chore

#91 [Chore] 로그 수집을 위한 xml 파일 수정
  src/main/resources/logback-spring.xml
Labels: 🛠️ Chore
